'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Skeleton } from '@/components/ui/skeleton'
import { toast } from 'sonner'
import { Plus, Swords, Download, Trash2, Edit, Sparkles, Loader2, RefreshCw, ExternalLink } from 'lucide-react'
import { timeAgo } from '@/lib/utils'
import Link from 'next/link'

interface OurFeature { id: string; name: string; productId: string }
interface Competitor {
  id: string
  name: string
  reportStatus?: string
  lastReportAt?: Date | null
  _count?: { managedSources: number; features: number }
}
interface BattleCard {
  id: string
  title: string
  ourFeature?: OurFeature | null
  competitorIdsJson: string[]
  strengthsText: string
  weaknessesText: string
  differentiatorsText: string
  salesMessagingText: string
  updatedAt: Date
}

interface Props {
  battleCards: BattleCard[]
  ourFeatures: OurFeature[]
  competitors: Competitor[]
  orgId: string
}

export function BattleCardsClient({ battleCards: initial, ourFeatures, competitors, orgId }: Props) {
  const router = useRouter()
  const [cards, setCards] = useState(initial)
  const [showCreate, setShowCreate] = useState(false)
  const [editCard, setEditCard] = useState<BattleCard | null>(null)
  const [saving, setSaving] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [form, setForm] = useState({
    title: '',
    ourFeatureId: '',
    competitorIds: [] as string[],
    strengthsText: '',
    weaknessesText: '',
    differentiatorsText: '',
    salesMessagingText: '',
  })

  const [refreshingId, setRefreshingId] = useState<string | null>(null)

  const handleRefreshFromReport = async (cardId: string) => {
    setRefreshingId(cardId)
    try {
      const res = await fetch(`/api/battle-cards/${cardId}/refresh-from-report`, { method: 'POST' })
      const data = await res.json()
      if (!res.ok) { toast.error(data.error ?? 'Refresh failed'); return }
      setCards((prev) => prev.map((c) => c.id === cardId ? { ...c, ...data } : c))
      toast.success(`Refreshed from ${data._refreshedFrom?.competitorName ?? 'report'}`)
    } catch {
      toast.error('Refresh failed')
    } finally {
      setRefreshingId(null)
    }
  }

  const resetForm = () => setForm({
    title: '', ourFeatureId: '', competitorIds: [],
    strengthsText: '', weaknessesText: '', differentiatorsText: '', salesMessagingText: '',
  })

  const openCreate = () => { resetForm(); setShowCreate(true) }
  const openEdit = (card: BattleCard) => {
    setEditCard(card)
    setForm({
      title: card.title,
      ourFeatureId: card.ourFeature?.id ?? '',
      competitorIds: card.competitorIdsJson,
      strengthsText: card.strengthsText,
      weaknessesText: card.weaknessesText,
      differentiatorsText: card.differentiatorsText,
      salesMessagingText: card.salesMessagingText,
    })
  }

  const handleGenerate = async () => {
    if (!form.ourFeatureId) { toast.error('Select a feature first'); return }
    setGenerating(true)
    try {
      const res = await fetch('/api/battle-cards', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...form, generate: true }),
      })
      if (!res.ok) throw new Error('Generate failed')
      const card = await res.json()
      setForm(prev => ({
        ...prev,
        strengthsText: card.strengthsText || '',
        weaknessesText: card.weaknessesText || '',
        differentiatorsText: card.differentiatorsText || '',
        salesMessagingText: card.salesMessagingText || '',
      }))
      toast.success('Battle card generated by AI')
    } catch {
      toast.error('AI generation failed')
    } finally {
      setGenerating(false)
    }
  }

  const handleSave = async () => {
    setSaving(true)
    try {
      const url = editCard ? `/api/battle-cards/${editCard.id}` : '/api/battle-cards'
      const method = editCard ? 'PUT' : 'POST'
      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      })
      if (!res.ok) throw new Error('Save failed')
      const saved = await res.json()
      if (editCard) {
        setCards(prev => prev.map(c => c.id === saved.id ? saved : c))
        setEditCard(null)
      } else {
        setCards(prev => [saved, ...prev])
        setShowCreate(false)
      }
      resetForm()
      toast.success(editCard ? 'Battle card updated' : 'Battle card created')
      router.refresh()
    } catch {
      toast.error('Failed to save battle card')
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async (id: string) => {
    if (!confirm('Delete this battle card?')) return
    const res = await fetch(`/api/battle-cards/${id}`, { method: 'DELETE' })
    if (res.ok) {
      setCards(prev => prev.filter(c => c.id !== id))
      toast.success('Deleted')
    } else {
      toast.error('Delete failed')
    }
  }

  const downloadCard = (card: BattleCard) => {
    const text = `# ${card.title}\n\n## Strengths\n${card.strengthsText}\n\n## Weaknesses\n${card.weaknessesText}\n\n## Differentiators\n${card.differentiatorsText}\n\n## Sales Messaging\n${card.salesMessagingText}`
    const blob = new Blob([text], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${card.title.replace(/\s+/g, '-').toLowerCase()}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const toggleCompetitor = (id: string) => {
    setForm(prev => ({
      ...prev,
      competitorIds: prev.competitorIds.includes(id)
        ? prev.competitorIds.filter(c => c !== id)
        : [...prev.competitorIds, id],
    }))
  }

  const FormContent = () => (
    <div className="space-y-4">
      <div>
        <Label>Title</Label>
        <Input value={form.title} onChange={e => setForm(p => ({ ...p, title: e.target.value }))} placeholder="e.g. vs Zendesk AI" />
      </div>
      <div>
        <Label>Our Feature</Label>
        <Select value={form.ourFeatureId} onValueChange={v => setForm(p => ({ ...p, ourFeatureId: v }))}>
          <SelectTrigger><SelectValue placeholder="Select feature" /></SelectTrigger>
          <SelectContent>
            {ourFeatures.map(f => (
              <SelectItem key={f.id} value={f.id}>{f.name}</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>
      <div>
        <Label>Competitors</Label>
        <div className="flex flex-wrap gap-2 mt-1">
          {competitors.map(c => (
            <button
              key={c.id}
              onClick={() => toggleCompetitor(c.id)}
              className={`px-3 py-1 rounded-full text-sm border transition-colors ${
                form.competitorIds.includes(c.id)
                  ? 'bg-primary text-primary-foreground border-primary'
                  : 'hover:bg-accent'
              }`}
            >
              {c.name}
            </button>
          ))}
        </div>
      </div>
      <Button variant="outline" size="sm" onClick={handleGenerate} disabled={generating} className="w-full">
        {generating ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Sparkles className="h-4 w-4 mr-2" />}
        Generate with AI
      </Button>
      <div>
        <Label>Strengths</Label>
        <Textarea value={form.strengthsText} onChange={e => setForm(p => ({ ...p, strengthsText: e.target.value }))} rows={3} placeholder="Our advantages..." />
      </div>
      <div>
        <Label>Weaknesses</Label>
        <Textarea value={form.weaknessesText} onChange={e => setForm(p => ({ ...p, weaknessesText: e.target.value }))} rows={3} placeholder="Areas to improve..." />
      </div>
      <div>
        <Label>Differentiators</Label>
        <Textarea value={form.differentiatorsText} onChange={e => setForm(p => ({ ...p, differentiatorsText: e.target.value }))} rows={3} placeholder="Key differentiators..." />
      </div>
      <div>
        <Label>Sales Messaging</Label>
        <Textarea value={form.salesMessagingText} onChange={e => setForm(p => ({ ...p, salesMessagingText: e.target.value }))} rows={3} placeholder="Objection handling and messaging..." />
      </div>
    </div>
  )

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Battle Cards</h1>
          <p className="text-muted-foreground text-sm mt-1">Sales-ready competitive positioning cards</p>
        </div>
        <Button onClick={openCreate}>
          <Plus className="h-4 w-4 mr-2" />
          New Battle Card
        </Button>
      </div>

      {cards.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-24 text-center">
          <Swords className="h-12 w-12 text-muted-foreground mb-4 opacity-40" />
          <h3 className="font-semibold text-lg">No battle cards yet</h3>
          <p className="text-muted-foreground text-sm mt-1">Create your first battle card to help your sales team</p>
          <Button className="mt-4" onClick={openCreate}>Create Battle Card</Button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {cards.map(card => (
            <Card key={card.id} className="hover:shadow-md transition-shadow">
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between gap-2">
                  <CardTitle className="text-base">{card.title}</CardTitle>
                  <div className="flex gap-1 shrink-0">
                    <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => downloadCard(card)}>
                      <Download className="h-3.5 w-3.5" />
                    </Button>
                    <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => openEdit(card)}>
                      <Edit className="h-3.5 w-3.5" />
                    </Button>
                    <Button variant="ghost" size="icon" className="h-7 w-7 text-destructive hover:text-destructive" onClick={() => handleDelete(card.id)}>
                      <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                  </div>
                </div>
                {card.ourFeature && (
                  <Badge variant="secondary" className="w-fit text-xs">{card.ourFeature.name}</Badge>
                )}
              </CardHeader>
              <CardContent className="text-sm space-y-3">
                {card.strengthsText && (
                  <div>
                    <p className="text-xs font-semibold text-green-600 uppercase tracking-wide mb-1">Strengths</p>
                    <p className="text-muted-foreground line-clamp-2">{card.strengthsText}</p>
                  </div>
                )}
                {card.differentiatorsText && (
                  <div>
                    <p className="text-xs font-semibold text-blue-600 uppercase tracking-wide mb-1">Differentiators</p>
                    <p className="text-muted-foreground line-clamp-2">{card.differentiatorsText}</p>
                  </div>
                )}
                <div className="pt-2 border-t mt-2 space-y-2">
                  <p className="text-xs text-muted-foreground">Updated {timeAgo(card.updatedAt)}</p>
                  {/* Linked competitors with report links */}
                  {card.competitorIdsJson.length > 0 && (() => {
                    const linkedCompetitors = competitors.filter((c) => card.competitorIdsJson.includes(c.id))
                    const hasReport = linkedCompetitors.some((c) => c.reportStatus === 'READY')
                    return (
                      <div className="flex items-center gap-2 flex-wrap">
                        {linkedCompetitors.map((c) => (
                          <Link
                            key={c.id}
                            href={`/competitors/${c.id}?tab=reports`}
                            className="inline-flex items-center gap-1 text-xs text-primary hover:underline"
                          >
                            <ExternalLink className="h-3 w-3" />{c.name}
                            {c.reportStatus === 'READY' && <span className="text-green-600">• report</span>}
                          </Link>
                        ))}
                        {hasReport && (
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-6 px-2 text-xs ml-auto"
                            onClick={() => handleRefreshFromReport(card.id)}
                            disabled={refreshingId === card.id}
                          >
                            {refreshingId === card.id
                              ? <Loader2 className="h-3 w-3 animate-spin mr-1" />
                              : <RefreshCw className="h-3 w-3 mr-1" />}
                            Refresh from Report
                          </Button>
                        )}
                      </div>
                    )
                  })()}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Create Dialog */}
      <Dialog open={showCreate} onOpenChange={setShowCreate}>
        <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>New Battle Card</DialogTitle>
          </DialogHeader>
          <FormContent />
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreate(false)}>Cancel</Button>
            <Button onClick={handleSave} disabled={saving || !form.title}>
              {saving ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
              Create
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Dialog */}
      <Dialog open={!!editCard} onOpenChange={v => !v && setEditCard(null)}>
        <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Edit Battle Card</DialogTitle>
          </DialogHeader>
          <FormContent />
          <DialogFooter>
            <Button variant="outline" onClick={() => setEditCard(null)}>Cancel</Button>
            <Button onClick={handleSave} disabled={saving}>
              {saving ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
              Save Changes
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
