import { NextResponse } from 'next/server'
import { getOrgId } from '@/lib/auth/utils'
import { prisma } from '@/lib/db'
import { getProductIdFromRequest } from '@/lib/product-context'
import { getAIClient } from '@/lib/ai/provider'

export async function GET(req: Request) {
  try {
    const orgId = await getOrgId()
    const productId = getProductIdFromRequest(req)
    const cards = await prisma.battleCard.findMany({
      where: { organizationId: orgId, ...(productId ? { productId } : {}) },
      include: { ourFeature: true, competitors: true },
      orderBy: { updatedAt: 'desc' },
    })
    return NextResponse.json(cards)
  } catch { return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }) }
}

export async function POST(req: Request) {
  try {
    const orgId = await getOrgId()
    const body = await req.json()
    const { ourFeatureId, competitorIds, generate } = body
    const productId = body.productId || getProductIdFromRequest(req)

    if (!generate) {
      // Manual creation
      const card = await prisma.battleCard.create({
        data: { organizationId: orgId, title: 'New Battle Card', ourFeatureId, competitorIdsJson: competitorIds ?? [], ...(productId ? { productId } : {}) },
      })
      return NextResponse.json(card, { status: 201 })
    }

    // AI generation
    const [ourFeature, competitors] = await Promise.all([
      ourFeatureId ? prisma.ourFeature.findFirst({ where: { id: ourFeatureId, product: { organizationId: orgId } } }) : null,
      prisma.competitor.findMany({
        where: { id: { in: competitorIds }, organizationId: orgId },
        include: { features: { take: 5 } },
      }),
    ])

    const aiClient = await getAIClient(orgId)
    const prompt = `Generate a competitive battle card for a B2B SaaS product.

Our Feature: ${ourFeature?.name ?? 'Our Product'}
Description: ${ourFeature?.description ?? ''}

Competitors:
${competitors.map((c) => `- ${c.name}: ${c.features.slice(0, 3).map((f) => f.name).join(', ')}`).join('\n')}

Return a JSON object with keys: title, strengthsText, weaknessesText, differentiatorsText, improvementOpportunitiesText, pmTakeawaysText, salesMessagingText, contentMd`

    const result = await aiClient.complete({
      model: aiClient.defaultModel,
      messages: [
        { role: 'system', content: 'You are a product strategist. Return valid JSON only.' },
        { role: 'user', content: prompt },
      ],
      jsonMode: true,
    })

    let parsed: any = {}
    try { parsed = JSON.parse(result.content) } catch {}

    const card = await prisma.battleCard.create({
      data: {
        organizationId: orgId,
        ...(productId ? { productId } : {}),
        title: parsed.title ?? `Battle Card: ${ourFeature?.name ?? 'Feature'}`,
        ourFeatureId,
        competitorIdsJson: competitorIds ?? [],
        competitorNamesJson: competitors.map((c) => c.name),
        strengthsText: parsed.strengthsText ?? '',
        weaknessesText: parsed.weaknessesText ?? '',
        differentiatorsText: parsed.differentiatorsText ?? '',
        improvementOpportunitiesText: parsed.improvementOpportunitiesText ?? '',
        pmTakeawaysText: parsed.pmTakeawaysText ?? '',
        salesMessagingText: parsed.salesMessagingText ?? '',
        contentMd: parsed.contentMd ?? result.content,
        autoGenerated: true,
        competitors: { connect: competitorIds.map((id: string) => ({ id })) },
      } as any,
    })
    return NextResponse.json(card, { status: 201 })
  } catch (e: any) {
    return NextResponse.json({ error: e.message ?? 'Error' }, { status: 500 })
  }
}
